# Generated by Django 3.0.4 on 2020-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hobbles',
            new_name='hobbies',
        ),
    ]
