# Generated by Django 3.0.4 on 2020-03-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_APP', '0003_auto_20200315_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='work_experience',
            old_name='user_id',
            new_name='userid',
        ),
    ]
