# Generated by Django 3.0.4 on 2020-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_APP', '0005_auto_20200317_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
